project:
  type: website
  output-dir: docs

website:
  title: "Huayu Liang"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/huayu1998
      - icon: twitter
        href: https://twitter.com/KiraLL98
      - icon: linkedin
        href: https://www.linkedin.com/in/huayu-liang-7ba623213/
        
  sidebar:
    style: "docked"
    search: true
    contents: auto
    
format:
  html:
    theme: 
      light: sketchy
      dark: superhero
    css: styles.css

editor: visual

